version: '3.8'

services:
  command-service:
    build:
      context: .
      dockerfile: ticketpick-command/Dockerfile
    container_name: ticketpick-command
    ports:
      - "8081:8081"
    networks:
      - ticketpick-network
    depends_on:
      - rabbitmq

  query-service:
    build:
      context: .
      dockerfile: ticketpick-query/Dockerfile
    container_name: ticketpick-query
    ports:
      - "8082:8082"
    networks:
      - ticketpick-network
    depends_on:
      - rabbitmq

  gateway:
    build:
      context: .
      dockerfile: ticketpick-gateway/Dockerfile
    container_name: ticketpick-gateway
    ports:
      - "8080:8080"
    networks:
      - ticketpick-network
    depends_on:
      - command-service
      - query-service

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticketpick-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - ticketpick-network

  prometheus:
    image: prom/prometheus:latest
    container_name: ticketpick-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ticketpick-network
    depends_on:
      - gateway
      - command-service
      - query-service

  grafana:
    image: grafana/grafana:latest
    container_name: ticketpick-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ticketpick-network
    depends_on:
      - prometheus

networks:
  ticketpick-network:
    driver: bridge
