spring:
  application:
    name: ticketpick-query
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  datasource:
    url: jdbc:h2:mem:ticketpick
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create  # create로 변경! (테이블 자동 생성)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # ⭐ 이게 핵심!
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8082
