spring:
  application:
    name: ticketpick-gateway
  
  cloud:
    gateway:
      routes:
        # Query - 경기
        - id: query-games
          uri: http://localhost:8082
          predicates:
            - Path=/api/games/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/query
        
        # Query - 좌석
        - id: query-seats
          uri: http://localhost:8082
          predicates:
            - Path=/api/seats/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/query
        
        # Command - 예매/취소
        - id: command-reservations
          uri: http://localhost:8081
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/command

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,gateway

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
