spring:
  application:
    name: ticketpick-gateway
  
  cloud:
    gateway:
      routes:
        - id: query-games
          uri: http://query-service:8082
          predicates:
            - Path=/api/games/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/query
        
        - id: query-seats
          uri: http://query-service:8082
          predicates:
            - Path=/api/seats/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/query
        
        - id: command-reservations
          uri: http://command-service:8081
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/command

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
